/*
 * Copyright (c) 2009 Xilinx, Inc.  All rights reserved.
 *
 * Xilinx, Inc.
 * XILINX IS PROVIDING THIS DESIGN, CODE, OR INFORMATION "AS IS" AS A
 * COURTESY TO YOU.  BY PROVIDING THIS DESIGN, CODE, OR INFORMATION AS
 * ONE POSSIBLE   IMPLEMENTATION OF THIS FEATURE, APPLICATION OR
 * STANDARD, XILINX IS MAKING NO REPRESENTATION THAT THIS IMPLEMENTATION
 * IS FREE FROM ANY CLAIMS OF INFRINGEMENT, AND YOU ARE RESPONSIBLE
 * FOR OBTAINING ANY RIGHTS YOU MAY REQUIRE FOR YOUR IMPLEMENTATION.
 * XILINX EXPRESSLY DISCLAIMS ANY WARRANTY WHATSOEVER WITH RESPECT TO
 * THE ADEQUACY OF THE IMPLEMENTATION, INCLUDING BUT NOT LIMITED TO
 * ANY WARRANTIES OR REPRESENTATIONS THAT THIS IMPLEMENTATION IS FREE
 * FROM CLAIMS OF INFRINGEMENT, IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

#ifndef _XPS_TFT_H_
#define _XPS_TFT_H_

#include "xparameters.h"
#include "xtft.h"

int xpstft_example();

#define XPS_TFT_0_VIDEO_MEMORY_ADDR    (XPAR_DDR2_SDRAM_MEM_BASEADDR + 0x01000000)
#define TFT_DEVICE_ID	XPAR_XPS_TFT_0_DEVICE_ID
#define UART_BASEADDR   XPAR_RS232_UART_1_BASEADDR
#define UART2_BASEADDR  XPAR_RS232_UART_2_BASEADDR
#define UART_BAUDRATE   XPAR_RS232_UART_1_BAUDRATE
#define UART_CLOCK      XPAR_XUARTNS550_CLOCK_HZ
#define TMRCTR_BASEADDR XPAR_XPS_TIMER_0_BASEADDR

#endif
